version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - JWT_SECRET
      - SUPER_ADMIN_ID
      - SUPER_ADMIN_PASSWORD
      - CORS_ALLOWED_ORIGINS
      - GCP_STORAGE_BUCKET
      - GOOGLE_APPLICATION_CREDENTIALS
      - GCP_PROJECT_ID
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql-data:
