version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SUPER_ADMIN_ID=${SUPER_ADMIN_ID}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - GCP_STORAGE_BUCKET=${GCP_STORAGE_BUCKET}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql-data:
